version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - DATABASE_URL=mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/portfolio_db?charset=utf8mb4
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - portfolio_network
    volumes:
      # 本番環境では静的ファイルのみマウント
      - ./static/uploads:/app/static/uploads
      - ./logs:/var/log

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: portfolio_db
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      # データの永続化
      - mysql_prod_data:/var/lib/mysql
      # 設定ファイル
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    restart: unless-stopped
    networks:
      - portfolio_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - ./static:/var/www/static:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - portfolio_network

volumes:
  mysql_prod_data:

networks:
  portfolio_network:
    driver: bridge