"""Add challenge_id to categories table

Revision ID: 0c9f70083eba
Revises: 8a8e7516e68a
Create Date: 2025-08-23 14:33:29.452758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9f70083eba'
down_revision = '8a8e7516e68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('challenge_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'challenges', ['challenge_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('challenge_id')

    # ### end Alembic commands ###
