"""Add professional portfolio fields to User model

Revision ID: 0ee10bce89e6
Revises: 2fa99c0a34e1
Create Date: 2025-08-25 09:08:06.520921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee10bce89e6'
down_revision = '2fa99c0a34e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tagline', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('resume_pdf', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('career_history', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('education', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('certifications', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('github_username', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('portfolio_email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('portfolio_email')
        batch_op.drop_column('github_username')
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('certifications')
        batch_op.drop_column('education')
        batch_op.drop_column('career_history')
        batch_op.drop_column('skills')
        batch_op.drop_column('resume_pdf')
        batch_op.drop_column('profile_photo')
        batch_op.drop_column('tagline')
        batch_op.drop_column('job_title')

    # ### end Alembic commands ###
