"""Add name_romaji field to User model

Revision ID: 239aa0fd9cab
Revises: 0ee10bce89e6
Create Date: 2025-08-25 15:00:25.036066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239aa0fd9cab'
down_revision = '0ee10bce89e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_romaji', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name_romaji')

    # ### end Alembic commands ###
