"""Add TOTP and password reset fields to User model

Revision ID: 29fb25fb7dc2
Revises: a34c8f5468ce
Create Date: 2025-06-15 14:19:12.927248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29fb25fb7dc2'
down_revision = 'a34c8f5468ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notify_on_publish', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_on_comment', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('introduction', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('birthplace', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('birthday', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('sns_accounts', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ext_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ext_json')
        batch_op.drop_column('sns_accounts')
        batch_op.drop_column('birthday')
        batch_op.drop_column('birthplace')
        batch_op.drop_column('introduction')
        batch_op.drop_column('notify_on_comment')
        batch_op.drop_column('notify_on_publish')
        batch_op.drop_column('reset_token_expires')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###
