"""Add demo_urls field for multiple demo URLs support

Revision ID: 2fa99c0a34e1
Revises: 0c9f70083eba
Create Date: 2025-08-24 16:50:20.702235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa99c0a34e1'
down_revision = '0c9f70083eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('demo_urls', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('demo_urls')

    # ### end Alembic commands ###
