"""Add email change request table

Revision ID: 4065a2c65a8e
Revises: 417f9d4aee75
Create Date: 2025-08-04 17:12:31.280279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4065a2c65a8e'
down_revision = '417f9d4aee75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_email', sa.String(length=255), nullable=False),
    sa.Column('new_email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_change_requests')
    # ### end Alembic commands ###
