"""Add SEOAnalysis table for LLMO and AIO analysis

Revision ID: 417f9d4aee75
Revises: 71094a0ba006
Create Date: 2025-07-12 16:13:27.790590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417f9d4aee75'
down_revision = '71094a0ba006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seo_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('analysis_data', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seo_analysis')
    # ### end Alembic commands ###
