"""Add manual days adjustment to Challenge model

Revision ID: 47e0cba9208e
Revises: cc229701a999
Create Date: 2025-08-22 15:16:24.656601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e0cba9208e'
down_revision = 'cc229701a999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('manual_adjustment_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_column('manual_adjustment_date')
        batch_op.drop_column('manual_days')

    # ### end Alembic commands ###
