"""Add StaticPageSEO model for static page SEO management

Revision ID: 80991d7d019d
Revises: 239aa0fd9cab
Create Date: 2025-08-30 09:33:54.688396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80991d7d019d'
down_revision = '239aa0fd9cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_page_seo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_slug', sa.String(length=50), nullable=False),
    sa.Column('page_name', sa.String(length=100), nullable=False),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.String(length=255), nullable=True),
    sa.Column('ogp_title', sa.String(length=255), nullable=True),
    sa.Column('ogp_description', sa.Text(), nullable=True),
    sa.Column('ogp_image', sa.String(length=255), nullable=True),
    sa.Column('ogp_image_alt', sa.String(length=255), nullable=True),
    sa.Column('canonical_url', sa.String(length=255), nullable=True),
    sa.Column('robots', sa.String(length=50), nullable=True),
    sa.Column('json_ld', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('static_page_seo')
    # ### end Alembic commands ###
