"""Update comments table schema with full comment fields

Revision ID: 8263ea2ff740
Revises: 29fb25fb7dc2
Create Date: 2025-06-15 15:33:39.215710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8263ea2ff740'
down_revision = '29fb25fb7dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('author_email', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('author_website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_comments_parent_id', 'comments', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_parent_id', type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('is_approved')
        batch_op.drop_column('content')
        batch_op.drop_column('author_website')
        batch_op.drop_column('author_email')
        batch_op.drop_column('author_name')

    # ### end Alembic commands ###
