"""Add project_ids to articles table for article-project relationship

Revision ID: 8a8e7516e68a
Revises: 266d4541b6c0
Create Date: 2025-08-23 12:07:15.574466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a8e7516e68a'
down_revision = '266d4541b6c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_ids', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('project_ids')

    # ### end Alembic commands ###
