"""Add Challenge model and update Article with challenge fields

Revision ID: ab4faf398a5a
Revises: bbb92912c6ea
Create Date: 2025-08-22 11:00:53.410974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4faf398a5a'
down_revision = 'bbb92912c6ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('target_days', sa.Integer(), nullable=True),
    sa.Column('github_repo', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('challenge_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('challenge_day', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'challenges', ['challenge_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('challenge_day')
        batch_op.drop_column('challenge_id')

    op.drop_table('challenges')
    # ### end Alembic commands ###
