"""Add missing SiteSetting table

Revision ID: bbb92912c6ea
Revises: 4065a2c65a8e
Create Date: 2025-08-21 17:43:22.654614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb92912c6ea'
down_revision = '4065a2c65a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('setting_type', sa.String(length=20), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('login_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legacy_body_backup', sa.Text(), nullable=True))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comments_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'articles', ['article_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('seo_analysis', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('seo_analysis_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'articles', ['article_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seo_analysis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('seo_analysis_ibfk_1'), 'articles', ['article_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comments_ibfk_1'), 'articles', ['article_id'], ['id'])

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('legacy_body_backup')

    op.drop_table('login_history')
    op.drop_table('site_settings')
    # ### end Alembic commands ###
