"""add show_toc field to Article model

Revision ID: c2215cf263fd
Revises: ecca9ec1a411
Create Date: 2025-08-30 11:47:02.070476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2215cf263fd'
down_revision = 'ecca9ec1a411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_toc', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('show_toc')

    # ### end Alembic commands ###
