"""Update Challenge model to support multiple GitHub repositories

Revision ID: cc229701a999
Revises: ab4faf398a5a
Create Date: 2025-08-22 11:09:22.430990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc229701a999'
down_revision = 'ab4faf398a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_repos', sa.Text(), nullable=True))
        batch_op.drop_column('github_repo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_repo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.drop_column('github_repos')

    # ### end Alembic commands ###
