"""Add json_ld field to Article model for structured data

Revision ID: ecca9ec1a411
Revises: 80991d7d019d
Create Date: 2025-08-30 10:46:30.050535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecca9ec1a411'
down_revision = '80991d7d019d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('json_ld', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('json_ld')

    # ### end Alembic commands ###
